using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Commander.Dtos
{
    public class CommandCreateDto
    {
        
        // We don't need to require the id since it is autogenerated
        /*
        Remember to include the attribute annotations from the model
        In case is not included it will send a server error instead of 
        bad request
        */
        [Required]
        public string HowTo { get; set; }
        public string Line { get; set; }
        public string Platform { get; set; }
    }
}
